### ISSUE TITLE
CexApiException: API key is not activated

### ISSUE THREAD

**Issue by zauradigozalov** [jordansjones/Cex.io-Api-Client#4]
Hi Jordans Jones,
First of all I would thank you for your work and it's very amazing. I've downloaded and tested this project. I'm able to access public functions. But I'm generated new api key and activated. Unfortunately I'm getting error as "CexApiException: API key is not activated". This api key works fine but is there something wrong posting and getting for Account Balance API?

Looking forward for your reply.

Thank you

**Comment by jordansjones** [comment]
@zauradigozalov sorry for the lengthy delay in responding, but if you are still running into this issue, I would refer to [Cex.io's help center](https://support.cex.io/hc/en-us). Specifically this page: https://support.cex.io/hc/en-us/articles/212083507-API-Setup-guide
